<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="php7" failures="2" tests="33" name="Default test" time="41.11" errors="0" timestamp="27 Mar 2021 09:26:05 GMT">
  <testcase classname="com.crm.qa.tests.LoginTests" name="Build1URL_Title" time="0.409"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="Build1_Title" time="0.041"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="Build2_Title" time="0.027"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="Email_Title" time="0.05"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="Email_URL" time="0.064"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="HotelImage1" time="0.094"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="HotelImage2" time="0.054"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="HotelImage3" time="0.102"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="HotelImage4" time="0.059"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="InvalideloginTest1" time="1.131"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="Password_Title" time="0.037"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="Signup" time="3.621"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="Signup_Title" time="0.046"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="Username_Title" time="0.036"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="ValideloginTest" time="1.63"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="build_title" time="0.045"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="footer_Title" time="0.04"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="forgotPass" time="0.989"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="forgotten_Title" time="0.045"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="hotel_URL" time="0.036"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="loginPageTitleTest" time="0.007"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="loginTitle" time="0.034"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="resetPassword" time="1.575"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="validateHeaderImg" time="0.055"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="validateImage" time="0.06"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="validateLOgo1" time="0.045"/>
  <testcase classname="com.crm.qa.tests.LoginTests" name="welcome_Title" time="0.042"/>
  <testcase classname="com.crm.qa.tests.ForgotTest" name="GoBack" time="0.002">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.crm.qa.pages.ForgotPage.GoBackLoginPage(ForgotPage.java:138)
	at com.crm.qa.tests.ForgotTest.GoBack(ForgotTest.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- GoBack -->
  <testcase classname="com.crm.qa.tests.SignUpTest" name="m" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [ytdruyhgrf] but found [Adactin.com - New User Registration]">
      <![CDATA[java.lang.AssertionError: expected [ytdruyhgrf] but found [Adactin.com - New User Registration]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.crm.qa.tests.SignUpTest.m(SignUpTest.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- m -->
  <testcase classname="com.crm.qa.tests.SignUpTest" name="register" time="0.0">
    <skipped/>
  </testcase> <!-- register -->
  <testcase classname="com.crm.qa.tests.HomeTest" name="locationDropDown1" time="0.0">
    <skipped/>
  </testcase> <!-- locationDropDown1 -->
  <testcase classname="com.crm.qa.tests.HomeTest" name="validateCheckInDate" time="0.179"/>
  <testcase classname="com.crm.qa.tests.HomeTest" name="validateCheckOutDate" time="0.165"/>
</testsuite> <!-- Default test -->
